
# Australian Government Agencies
# AI Transparency Statement URLs

[[agencies]]
name = "Digital Transformation Agency"
abbr = "DTA"
size = "medium"
url = "https://www.dta.gov.au/ai-transparency-statement"

[[agencies]]
name = "Treasury"
abbr = "TREASURY"
size = "medium"
url = "https://treasury.gov.au/the-department/accountability-reporting/ai-transparency-statement"

[[agencies]]
name = "Department of Agriculture, Fisheries and Forestry"
abbr = "DAFF"
size = "medium"
url = "https://www.agriculture.gov.au/about/reporting/obligations/AI-transparency-statement"

[[agencies]]
name = "Department of Health and Aged Care"
abbr = "DHAC"
size = "medium"
url = "https://www.health.gov.au/about-us/corporate-reporting/our-commitments/ai-transparency-statement"

[[agencies]]
name = "National Indigenous Australians Agency"
abbr = "NIAA"
size = "medium"
url = "https://www.niaa.gov.au/artificial-intelligence-ai-transparency-statement"

[[agencies]]
name = "Australian Institute of Criminology"
abbr = "AIC"
size = "unknown"
url = "https://www.aic.gov.au/about-us/artificial-intelligence-ai-transparency-statement"

[[agencies]]
name = "Australian Securities and Investments Commission"
abbr = "ASIC"
size = "unknown"
url = "https://www.asic.gov.au/about-asic/what-we-do/how-we-operate/accountability-and-reporting/artificial-intelligence-transparency-statement/"

[[agencies]]
name = "Department of Education"
abbr = "EDUCATION"
size = "medium"
url = "https://www.education.gov.au/about-department/corporate-reporting/artificial-intelligence-ai-transparency-statement"

[[agencies]]
name = "Department of Home Affairs"
abbr = "HOMEAFFAIRS"
size = "extra-large"
url = "https://www.homeaffairs.gov.au/commitments/files/ai-transparency-statement.pdf"

[[agencies]]
name = "Aboriginal Hostels Limited"
abbr = "AHL"
size = "medium"
url = "https://www.aboriginal-hostels-limited.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Administrative Review Tribunal"
abbr = "ART"
size = "medium"
url = "https://www.art.gov.au/ai-transparency-statement"

[[agencies]]
name = "Aged Care Quality and Safety Commission"
abbr = "ACQSC"
size = "medium"
url = "https://www.agedcarequality.gov.au/sites/default/files/media/acqsc_ai_transparency_statement.pdf"

[[agencies]]
name = "Asbestos and Silica Safety and Eradication Agency"
abbr = "ASSEA"
size = "extra-small"
url = ""

[[agencies]]
name = "Attorney-General's Department"
abbr = "AGD"
size = "medium"
url = "https://www.ag.gov.au/about-us/accountability-and-reporting/attorney-generals-department-artificial-intelligence-transparency-statement"

[[agencies]]
name = "Australian Bureau of Statistics"
abbr = "ABS"
size = "medium"
url = "https://www.abs.gov.au/about/legislation-and-policy/ai-transparency-statement"

[[agencies]]
name = "Australian Centre for International Agricultural Research"
abbr = "ACIAR"
size = "extra-small"
url = "https://www.ciar.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Commission on Safety and Quality in Health Care"
abbr = "ACSQHC"
size = "small"
url = ""

[[agencies]]
name = "Australian Communications and Media Authority"
abbr = "ACMA"
size = "medium"
url = "https://www.acma.gov.au/planning-and-priorities"

[[agencies]]
name = "Australian Competition and Consumer Commission"
abbr = "ACCC"
size = "medium"
url = "https://www.accc.gov.au/about-us/accc-role-and-structure/governance-and-accountability/artificial-intelligence-ai-transparency-statement"

[[agencies]]
name = "Australian Criminal Intelligence Commission"
abbr = "ACIC"
size = "medium"
url = "https://www.criminal-intelligence.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Digital Health Agency"
abbr = "ADHA"
size = "medium"
url = "https://www.digitalhealth.gov.au/about-us/policies-privacy-and-reporting/artificial-intelligence-transparency-statement"

[[agencies]]
name = "Australian Electoral Commission"
abbr = "AEC"
size = "medium"
url = "https://www.aec.gov.au/Elections/electoral-advertising/ai-and-elections.htm"

[[agencies]]
name = "Australian Financial Security Authority"
abbr = "AFSA"
size = "medium"
url = "https://www.afsa.gov.au/about-us/accountability-and-reporting/ai-transparency-statement"

[[agencies]]
name = "Australian Fisheries Management Authority"
abbr = "AFMA"
size = "small"
url = "https://www.afma.gov.au/reporting-and-accountability/artificial-intelligence-transparency-statement"

[[agencies]]
name = "Australian Human Rights Commission"
abbr = "AHRC"
size = "small"
url = ""

[[agencies]]
name = "Australian Institute of Aboriginal and Torres Strait Islander Studies"
abbr = "AIATSIS"
size = "small"
url = ""

[[agencies]]
name = "Australian Institute of Family Studies"
abbr = "AIFS"
size = "small"
url = "https://aifs.gov.au/main/policies/ai-transparency-statement"

[[agencies]]
name = "Australian Institute of Health and Welfare"
abbr = "AIHW"
size = "medium"
url = "https://www.ihw.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Law Reform Commission"
abbr = "ALRC"
size = "extra-small"
url = ""

[[agencies]]
name = "Australian National Audit Office"
abbr = "ANAO"
size = "medium"
url = "https://www.anao.gov.au/work/corporate/anaos-artificial-intelligence-transparency-statement"

[[agencies]]
name = "Australian National Maritime Museum"
abbr = "ANMM"
size = "small"
url = ""

[[agencies]]
name = "Australian Office of Financial Management"
abbr = "AOFM"
size = "extra-small"
url = "https://www.office-of-financial-management.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Pesticides and Veterinary Medicines Authority"
abbr = "APVMA"
size = "small"
url = "https://www.pvm.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Public Service Commission"
abbr = "APSC"
size = "medium"
url = "https://www.public-service.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Radiation Protection and Nuclear Safety Agency"
abbr = "ARPANSA"
size = "small"
url = "https://www.rpns.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Research Council"
abbr = "ARC"
size = "small"
url = "https://www.research-council.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Skills Quality Authority"
abbr = "ASQA"
size = "medium"
url = "https://www.skills-quality.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Submarine Agency"
abbr = "ASA"
size = "medium"
url = "https://www.submarine.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Taxation Office"
abbr = "ATO"
size = "extra-large"
url = "https://www.ato.gov.au/about-ato/commitments-and-reporting/information-and-privacy/ato-ai-transparency-statement"

[[agencies]]
name = "Australian Trade and Investment Commission"
abbr = "AUSTRADE"
size = "medium"
url = "https://www.trade-and-investment.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Transaction Reports and Analysis Centre"
abbr = "AUSTRAC"
size = "medium"
url = "https://www.trac.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian Transport Safety Bureau"
abbr = "ATSB"
size = "small"
url = "https://www.transport-safety-bureau.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Australian War Memorial"
abbr = "AWM"
size = "medium"
url = "https://www.war-memorial.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Bureau of Meteorology"
abbr = "BOM"
size = "medium"
url = ""

[[agencies]]
name = "Cancer Australia"
abbr = "CA"
size = "extra-small"
url = "https://www.cancer-australia.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Clean Energy Regulator"
abbr = "CER"
size = "medium"
url = "https://www.clean-energy-regulator.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Climate Change Authority"
abbr = "CCA"
size = "extra-small"
url = "https://www.climate-change.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Comcare"
abbr = "COMCARE"
size = "medium"
url = "https://www.comcare.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Commonwealth Director of Public Prosecutions"
abbr = "CDPP"
size = "medium"
url = "https://www.cdpp.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Commonwealth Grants Commission"
abbr = "CGC"
size = "extra-small"
url = "https://www.commonwealth-grants.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Defence Housing Australia"
abbr = "DHA"
size = "medium"
url = "https://www.defence-housing-australia.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Department of Climate Change, Energy, the Environment and Water"
abbr = "DCCEEW"
size = "medium"
url = "https://cceew.gov.au/about/accountability-reporting/ai-transparency-statement"

[[agencies]]
name = "Department of Defence"
abbr = "DEFENCE"
size = "extra-large"
url = ""

[[agencies]]
name = "Department of Employment and Workplace Relations"
abbr = "DEWR"
size = "medium"
url = "https://www.dewr.gov.au/about-department/corporate-reporting/dewr-ai-transparency-statement"

[[agencies]]
name = "Department of Finance"
abbr = "FINANCE"
size = "medium"
url = "https://www.finance.gov.au/about-us/artificial-intelligence-ai-transparency-statement"

[[agencies]]
name = "Department of Foreign Affairs and Trade"
abbr = "DFAT"
size = "medium"
url = "https://www.dfat.gov.au/about-us/corporate/artificial-intelligence-ai-transparency-statement"

[[agencies]]
name = "Department of Health, Disability and Ageing"
abbr = "DHDA"
size = "medium"
url = "https://health-disability-and-ageing.gov.au/about/accountability-reporting/ai-transparency-statement"

[[agencies]]
name = "Department of Industry, Science and Resources"
abbr = "DISR"
size = "medium"
url = "https://industry-science-and-resources.gov.au/about/accountability-reporting/ai-transparency-statement"

[[agencies]]
name = "Department of Infrastructure, Transport, Regional Development, Communications, Sport and the Arts"
abbr = "DITRDCA"
size = "medium"
url = "https://itrdcsa.gov.au/about/accountability-reporting/ai-transparency-statement"

[[agencies]]
name = "Department of Social Services"
abbr = "DSS"
size = "medium"
url = "https://www.dss.gov.au/doing-business-us/corporate-policies/artificial-intelligence-ai-transparency-statement"

[[agencies]]
name = "Department of Veterans' Affairs"
abbr = "DVA"
size = "medium"
url = "https://veterans-affairs.gov.au/about/accountability-reporting/ai-transparency-statement"

[[agencies]]
name = "Department of the Prime Minister and Cabinet"
abbr = "PMC"
size = "medium"
url = "https://www.pmc.gov.au/about-us/accountability-and-reporting/corporate-reporting/artificial-intelligence-ai-transparency-statement"

[[agencies]]
name = "Domestic, Family and Sexual Violence Commission"
abbr = "DFSVC"
size = "extra-small"
url = "https://www.dfsv.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Fair Work Commission"
abbr = "FWC"
size = "medium"
url = "https://www.fair-work.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Fair Work Ombudsman"
abbr = "FWO"
size = "medium"
url = "https://www.fair-work-ombudsman.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Federal Court of Australia"
abbr = "FCA"
size = "medium"
url = "https://www.federal-court-of-australia.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Food Standards Australia New Zealand"
abbr = "FSANZ"
size = "small"
url = "https://www.fsanz.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Future Fund Management Agency"
abbr = "FFMA"
size = "medium"
url = "https://www.future-fund-management.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Geoscience Australia"
abbr = "GA"
size = "medium"
url = "https://www.geoscience-australia.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Great Barrier Reef Marine Park Authority"
abbr = "GBRMPA"
size = "small"
url = "https://www.great-barrier-reef-marine-park.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "High Speed Rail Authority"
abbr = "HSRA"
size = "extra-small"
url = "https://www.high-speed-rail.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "IP Australia"
abbr = "IPA"
size = "medium"
url = "https://www.ip-australia.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Independent Parliamentary Expenses Authority"
abbr = "IPEA"
size = "extra-small"
url = "https://www.independent-parliamentary-expenses.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Inspector-General of Taxation and Taxation Ombudsman"
abbr = "IGTO"
size = "extra-small"
url = "https://www.igtto.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Murray Darling Basin Authority"
abbr = "MDBA"
size = "medium"
url = "https://www.murray-darling-basin.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Museum of Australian Democracy at Old Parliament House"
abbr = "MOADOPH"
size = "small"
url = "https://www.madaoph.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "NDIS Quality and Safeguards Commission"
abbr = "NDISQSC"
size = "medium"
url = "https://www.ndis-quality-and-safeguards.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Anti-Corruption Commission"
abbr = "NACC"
size = "small"
url = "https://www.national-anti-corruption.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Archives Australia"
abbr = "NAA"
size = "medium"
url = "https://www.national-archives-australia.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Blood Authority"
abbr = "NBA"
size = "extra-small"
url = "https://www.national-blood.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Capital Authority"
abbr = "NCA"
size = "extra-small"
url = "https://www.national-capital.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Commission for Aboriginal and Torres Strait Islander Children and Young People"
abbr = "NCATSICYP"
size = "micro"
url = "https://www.ncatsicyp.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Disability Insurance Agency"
abbr = "NDIA"
size = "extra-large"
url = ""

[[agencies]]
name = "National Emergency Management Agency"
abbr = "NEMA"
size = "medium"
url = "https://www.national-emergency-management.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Film and Sound Archive of Australia"
abbr = "NFSA"
size = "medium"
url = "https://www.nfsaa.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Health Funding Body"
abbr = "NHFB"
size = "extra-small"
url = "https://www.national-health-funding-body.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Health and Medical Research Council"
abbr = "NHMRC"
size = "medium"
url = "https://www.nhmrc.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Library of Australia"
abbr = "NLA"
size = "medium"
url = "https://www.national-library-of-australia.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Museum of Australia"
abbr = "NMA"
size = "medium"
url = "https://www.national-museum-of-australia.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Offshore Petroleum Safety and Environmental Management Authority"
abbr = "NOPSEMA"
size = "small"
url = "https://www.nopsem.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "National Portrait Gallery of Australia"
abbr = "NGA"
size = "extra-small"
url = "https://www.npga.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Office of National Intelligence"
abbr = "ONI"
size = "medium"
url = "https://www.oni.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Office of Parliamentary Counsel"
abbr = "OPC"
size = "small"
url = "https://www.opc.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Office of the Australian Information Commissioner"
abbr = "OAIC"
size = "small"
url = "https://www.oaic.gov.au/about-the-OAIC/our-corporate-information/oaic-ai-transparency-statement"

[[agencies]]
name = "Office of the Commonwealth Ombudsman"
abbr = "OCO"
size = "medium"
url = "https://www.oco.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Office of the Inspector-General of Aged Care"
abbr = "OIGAC"
size = "extra-small"
url = "https://www.oigac.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Office of the Inspector-General of Intelligence and Security"
abbr = "IGIS"
size = "extra-small"
url = "https://www.oigis.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Office of the Special Investigator"
abbr = "OSI"
size = "micro"
url = "https://www.osi.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Organ and Tissue Authority"
abbr = "OTA"
size = "extra-small"
url = "https://www.organ-and-tissue.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Parliamentary Workplace Support Service"
abbr = "PWSS"
size = "extra-small"
url = "https://www.pwss.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Productivity Commission"
abbr = "PC"
size = "small"
url = "https://www.productivity.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Professional Services Review"
abbr = "PSR"
size = "extra-small"
url = "https://www.professional-services-review.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Royal Australian Mint"
abbr = "RAM"
size = "medium"
url = "https://www.royal-australian-mint.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Safe Work Australia"
abbr = "SWA"
size = "small"
url = "https://www.safe-work-australia.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Screen Australia"
abbr = "SA"
size = "micro"
url = "https://www.screen-australia.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Services Australia"
abbr = "SERVICESAUSTRALIA"
size = "extra-large"
url = "https://www.servicesaustralia.gov.au/automation-and-artificial-intelligence-transparency-statement"

[[agencies]]
name = "Sport Integrity Australia"
abbr = "SIA"
size = "small"
url = "https://www.sport-integrity-australia.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Tertiary Education Quality and Standards Agency"
abbr = "TEQSA"
size = "small"
url = "https://www.teqs.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Torres Strait Regional Authority"
abbr = "TSRA"
size = "small"
url = "https://www.torres-strait-regional.gov.au/about-us/ai-transparency-statement"

[[agencies]]
name = "Workplace Gender Equality Agency"
abbr = "WGEA"
size = "extra-small"
url = "https://www.workplace-gender-equality.gov.au/about-us/ai-transparency-statement"
